import { createElement } from '@lwc/engine-dom';
import DF25_Conversation_Simulator from 'c/dF25_Conversation_Simulator';

describe('c-d-f-25-conversation-simulator', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-d-f-25-conversation-simulator', {
            is: DF25_Conversation_Simulator
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});